FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Bazaar API

## TODOS
+ filter list API endpoints
+ filter facet API endpoint
+ upload API endpoints
+ authentication
+ API versioning
+ paging - use timestamp or sequence param, [next & prev links](http://www.rfc-editor.org/rfc/rfc5988.txt) via Link headers?
+ describe request / response attributes
+ user id or slug for user owned resources?


# Group Items

# Items [/items]

[Status flow](https://www.gliffy.com/go/publish/8739555) of item.

+ Model (application/json)

    + Body
    
            {
                "id": 10,
                "status": "active",
                "slug": "fender-telecaster-mexiko",
                "name": "Fender Precision Bass",
                "images": [
                    {
                        "full": "http://lorempixel.com/1600/1200/",
                        "thumb": "http://lorempixel.com/300/200/"
                    },
                    {
                        "full": "http://lorempixel.com/1600/1200/",
                        "thumb": "http://lorempixel.com/300/200/"
                    }
                ],
                "district": "Královehradecký kraj",
                "price": 20000,
                "description": "",
                "personalPickupOnly": true,
                "created": "2013-12-12 12:45:30",
                "url": "/items/10"
            }


## List items [GET /items{?start,limit,filterCategory,filterPrice,filterPlace,filterRadius}]

Only *active* items are listed.

+ Parameters
    + start (string, optional) - _TODO_ timestamp or sequence based - we will use it for paging.
    + limit (integer,optional)
        + default: `30`
    + filterCategory: `kytary/elektricke-kytary` (string,optional)
    + filterPrice: `1000-2500` (string,optional) - Price range from predefined set.
    + filterPlace: `50.075,14.437` (string,optional) - GPS coordinates
    + filterRadius: `1-5km` (string,optional) - Radius range from predefined set. Makes sense only if *filterPlace* param is set. 

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/1"
          },
          {
            "id": 2,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/2"
          },
          {
            "id": 3,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/3"
          },
          {
            "id": 4,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/4"
          },
          {
            "id": 5,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/5"
          },
          {
            "id": 6,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/6"
          },
          {
            "id": 7,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/7"
          },
          {
            "id": 8,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/8"
          },
          {
            "id": 9,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixdel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/9"
          },
          {
            "id": 10,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/10"
          }
        ]
        
## Get specific item [GET /items/{id}]

+ Parameters
    + id: `2` (integer)
    
+ Response 200
    
    [Items][]


## Create item [POST /items]
  
 
+ Request (application/json)
        
        {
            "name": "Fender Precision Bass",
            "images": ["252bafe554121d4f7a391234ceda001fd64c69bd"],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "personalPickupOnly": true
          }
+ Response 201
    
    [Items][]


## Update item [PUT /items/{id}]

+ Parameters
    + id: `2` (integer)
              
+ Response 204

## Delete item [DELETE /items/{id}]

+ Parameters
    + id: `2` (integer)
              
+ Response 204


# Upload [/uploads]

## Upload image [POST /uploads/images]

+ Response 201 (application/json)

        {
            "id": "252bafe554121d4f7a391234ceda001fd64c69bd",
            "url": "/uploads/images/252bafe554121d4f7a391234ceda001fd64c69bd"
        }
        
        

# Group User

# Watchdogs [/user/{userId}/watchdogs]

## List users watchdogs [GET]

+ Parameters
    + userId: `2` (integer)
              
+ Response 200 (application/json)

        [
            {
                "hash": "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3",
                "url": "/user/2/watchdogs/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"
                "query": "marshall",
                "filterCategory": "kytary/elektricke-kytary",
                "filterPrice": "10000-25000",
            },
            {
                "hash": "b94a8fe5ccb19ba61c4c0873d391e987982fbbd3",
                "url": "/user/2/watchdogs/b94a8fe5ccb19ba61c4c0873d391e987982fbbd3"
                "query": "tubescreamer",
                "filterCategory": "kytary/kytarove-efekty",
                "filterPrice": "1000-5000",
            }
        ]


## Create new watchdog [POST /user/{userId}/watchdogs]

Hash of filter key / values is automaticaly created (same filter setting results in same hash).

+ Parameters
    + userId: `2` (integer)

+ Request

        {
            "query": "marshall",
            "filterCategory": "kytary/elektricke-kytary",
            "filterPrice": "1000-5000",
        }
        
+ Response 201 (application/json)
        
        {
            "hash": "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3",
            "url": "/user/2/watchdogs/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"
            "query": "marshall",
            "filterCategory": "kytary/elektricke-kytary",
            "filterPrice": "1000-5000",
        }

## Delete watchdog [DELETE /user/{userId}/watchdogs/{hash}]
+ Parameters
    + userId: `2` (integer)
    + hash: `a94a8fe5ccb19ba61c4c0873d391e987982fbbd3` (string)

+ Response 204

