FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Bazaar API

# Group Items

# Items /items{?start,limit,filterPrice,filterPlace,filterRadius}
+ Parameters
    + limit (integer,optional)
        + default: `30`
    + start (string, optional) - TODO
    + filterPrice: `1000-2500` (string,optional) - Price range from predefined set.
    + filterPlace: `50.075,14.437` (string,optional) - GPS coordinates
    + filterRadius: `1-5km` (string,optional) - Radius range from predefined set. Makes sense only if *filterPlace* param is set. 

## List items [GET]
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/1"
          },
          {
            "id": 2,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/2"
          },
          {
            "id": 3,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/3"
          },
          {
            "id": 4,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/4"
          },
          {
            "id": 5,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/5"
          },
          {
            "id": 6,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/6"
          },
          {
            "id": 7,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/7"
          },
          {
            "id": 8,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/8"
          },
          {
            "id": 9,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Telecaster Mexico",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Olomoucký kraj",
            "price": 13000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/9"
          },
          {
            "id": 10,
            "slug": "fender-telecaster-mexiko",
            "name": "Fender Precision Bass",
            "images": [
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                },
                {
                    "full": "http://lorempixel.com/1600/1200/",
                    "thumb": "http://lorempixel.com/300/200/"
                }
            ],
            "district": "Královehradecký kraj",
            "price": 20000,
            "description": "",
            "created": "2013-12-12 12:45:30",
            "url": "/items/10"
          }
        ]
              